export const EVENT_START = "EVENT_START";
export const EVENT_FAIL = "EVENT_FAIL";

export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const GET_EVENT = "GET_EVENT";
export const GET_SINGLE_EVENT = "GET_SINGLE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
