export const FEEDBACK_START = "FEEDBACK_START";
export const FEEDBACK_FAIL = "FEEDBACK_FAIL";
export const FEEDBACK_CREATE_SUCCESS = "FEEDBACK_CREATE_SUCCESS";
export const FEEDBACK_GET_SUCCESS = "FEEDBACK_GET_SUCCESS";
export const FEEDBACK_UPDATE_SUCCESS = "FEEDBACK_UPDATE_SUCCESS";
