export const country = [
  {
    id: 1,
    name: "Afghanistan",
    shortName: "AF",
    continent: "Asia",
    zone: "South Asia",
  },
  {
    id: 2,
    name: "Albania",
    shortName: "AL",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 3,
    name: "Algeria",
    shortName: "DZ",
    continent: "Africa",
    zone: "Northern Africa",
  },
  {
    id: 4,
    name: "Andorra",
    shortName: "AD",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 5,
    name: "Angola",
    shortName: "AO",
    continent: "Africa",
    zone: "Middle Africa",
  },
  {
    id: 6,
    name: "Antigua and Barbuda",
    shortName: "AG",
    continent: "North America",
    zone: "Caribbean",
  },
  {
    id: 7,
    name: "Argentina",
    shortName: "AR",
    continent: "South America",
    zone: "South America",
  },
  {
    id: 8,
    name: "Armenia",
    shortName: "AM",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 9,
    name: "Australia",
    shortName: "AU",
    continent: "Oceania",
    zone: "Australia",
  },
  {
    id: 10,
    name: "Austria",
    shortName: "AT",
    continent: "Europe",
    zone: "Western Europe",
  },
  {
    id: 11,
    name: "Azerbaijan",
    shortName: "AZ",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 12,
    name: "Bahamas",
    shortName: "BS",
    continent: "North America",
    zone: "Caribbean",
  },
  {
    id: 13,
    name: "Bahrain",
    shortName: "BH",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 14,
    name: "Bangladesh",
    shortName: "BD",
    continent: "Asia",
    zone: "South Asia",
  },
  {
    id: 15,
    name: "Barbados",
    shortName: "BB",
    continent: "North America",
    zone: "Caribbean",
  },
  {
    id: 16,
    name: "Belarus",
    shortName: "BY",
    continent: "Europe",
    zone: "Eastern Europe",
  },
  {
    id: 17,
    name: "Belgium",
    shortName: "BE",
    continent: "Europe",
    zone: "Western Europe",
  },
  {
    id: 18,
    name: "Belize",
    shortName: "BZ",
    continent: "North America",
    zone: "Central America",
  },
  {
    id: 19,
    name: "Benin",
    shortName: "BJ",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 20,
    name: "Bhutan",
    shortName: "BT",
    continent: "Asia",
    zone: "South Asia",
  },
  {
    id: 21,
    name: "Bolivia",
    shortName: "BO",
    continent: "South America",
    zone: "South America",
  },
  {
    id: 22,
    name: "Bosnia and Herzegovina",
    shortName: "BA",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 23,
    name: "Botswana",
    shortName: "BW",
    continent: "Africa",
    zone: "Southern Africa",
  },
  {
    id: 24,
    name: "Brazil",
    shortName: "BR",
    continent: "South America",
    zone: "South America",
  },
  {
    id: 25,
    name: "Brunei",
    shortName: "BN",
    continent: "Asia",
    zone: "Southeast Asia",
  },
  {
    id: 26,
    name: "Bulgaria",
    shortName: "BG",
    continent: "Europe",
    zone: "Eastern Europe",
  },
  {
    id: 27,
    name: "Burkina Faso",
    shortName: "BF",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 28,
    name: "Burundi",
    shortName: "BI",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 29,
    name: "Cabo Verde",
    shortName: "CV",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 30,
    name: "Cambodia",
    shortName: "KH",
    continent: "Asia",
    zone: "Southeast Asia",
  },
  {
    id: 31,
    name: "Cameroon",
    shortName: "CM",
    continent: "Africa",
    zone: "Middle Africa",
  },
  {
    id: 32,
    name: "Canada",
    shortName: "CA",
    continent: "North America",
    zone: "North America",
  },
  {
    id: 33,
    name: "Central African Republic",
    shortName: "CF",
    continent: "Africa",
    zone: "Middle Africa",
  },
  {
    id: 34,
    name: "Chad",
    shortName: "TD",
    continent: "Africa",
    zone: "Middle Africa",
  },
  {
    id: 35,
    name: "Chile",
    shortName: "CL",
    continent: "South America",
    zone: "South America",
  },
  {
    id: 36,
    name: "China",
    shortName: "CN",
    continent: "Asia",
    zone: "Eastern Asia",
  },
  {
    id: 37,
    name: "Colombia",
    shortName: "CO",
    continent: "South America",
    zone: "South America",
  },
  {
    id: 38,
    name: "Comoros",
    shortName: "KM",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 39,
    name: "Congo (Congo-Brazzaville)",
    shortName: "CG",
    continent: "Africa",
    zone: "Middle Africa",
  },
  {
    id: 40,
    name: "Costa Rica",
    shortName: "CR",
    continent: "North America",
    zone: "Central America",
  },
  {
    id: 41,
    name: "Croatia",
    shortName: "HR",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 42,
    name: "Cuba",
    shortName: "CU",
    continent: "North America",
    zone: "Caribbean",
  },
  {
    id: 43,
    name: "Cyprus",
    shortName: "CY",
    continent: "Europe",
    zone: "Western Asia",
  },
  {
    id: 44,
    name: "Czech Republic",
    shortName: "CZ",
    continent: "Europe",
    zone: "Eastern Europe",
  },
  {
    id: 45,
    name: "Denmark",
    shortName: "DK",
    continent: "Europe",
    zone: "Northern Europe",
  },
  {
    id: 46,
    name: "Djibouti",
    shortName: "DJ",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 47,
    name: "Dominica",
    shortName: "DM",
    continent: "North America",
    zone: "Caribbean",
  },
  {
    id: 48,
    name: "Dominican Republic",
    shortName: "DO",
    continent: "North America",
    zone: "Caribbean",
  },
  {
    id: 49,
    name: "Ecuador",
    shortName: "EC",
    continent: "South America",
    zone: "South America",
  },
  {
    id: 50,
    name: "Egypt",
    shortName: "EG",
    continent: "Africa",
    zone: "Northern Africa",
  },
  {
    id: 51,
    name: "El Salvador",
    shortName: "SV",
    continent: "North America",
    zone: "Central America",
  },
  {
    id: 52,
    name: "Equatorial Guinea",
    shortName: "GQ",
    continent: "Africa",
    zone: "Middle Africa",
  },
  {
    id: 53,
    name: "Eritrea",
    shortName: "ER",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 54,
    name: "Estonia",
    shortName: "EE",
    continent: "Europe",
    zone: "Northern Europe",
  },
  {
    id: 55,
    name: "Eswatini",
    shortName: "SZ",
    continent: "Africa",
    zone: "Southern Africa",
  },
  {
    id: 56,
    name: "Ethiopia",
    shortName: "ET",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 57,
    name: "Fiji",
    shortName: "FJ",
    continent: "Oceania",
    zone: "Melanesia",
  },
  {
    id: 58,
    name: "Finland",
    shortName: "FI",
    continent: "Europe",
    zone: "Northern Europe",
  },
  {
    id: 59,
    name: "France",
    shortName: "FR",
    continent: "Europe",
    zone: "Western Europe",
  },
  {
    id: 60,
    name: "Gabon",
    shortName: "GA",
    continent: "Africa",
    zone: "Middle Africa",
  },
  {
    id: 61,
    name: "Gambia",
    shortName: "GM",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 62,
    name: "Georgia",
    shortName: "GE",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 63,
    name: "Germany",
    shortName: "DE",
    continent: "Europe",
    zone: "Western Europe",
  },
  {
    id: 64,
    name: "Ghana",
    shortName: "GH",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 65,
    name: "Greece",
    shortName: "GR",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 66,
    name: "Grenada",
    shortName: "GD",
    continent: "North America",
    zone: "Caribbean",
  },
  {
    id: 67,
    name: "Guatemala",
    shortName: "GT",
    continent: "North America",
    zone: "Central America",
  },
  {
    id: 68,
    name: "Guinea",
    shortName: "GN",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 69,
    name: "Guinea-Bissau",
    shortName: "GW",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 70,
    name: "Guyana",
    shortName: "GY",
    continent: "South America",
    zone: "South America",
  },
  {
    id: 71,
    name: "Haiti",
    shortName: "HT",
    continent: "North America",
    zone: "Caribbean",
  },
  {
    id: 72,
    name: "Holy See",
    shortName: "VA",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 73,
    name: "Honduras",
    shortName: "HN",
    continent: "North America",
    zone: "Central America",
  },
  {
    id: 74,
    name: "Hungary",
    shortName: "HU",
    continent: "Europe",
    zone: "Eastern Europe",
  },
  {
    id: 75,
    name: "Iceland",
    shortName: "IS",
    continent: "Europe",
    zone: "Northern Europe",
  },
  {
    id: 76,
    name: "India",
    shortName: "IN",
    continent: "Asia",
    zone: "Southern Asia",
  },
  {
    id: 77,
    name: "Indonesia",
    shortName: "ID",
    continent: "Asia",
    zone: "Southeast Asia",
  },
  {
    id: 78,
    name: "Iran (Islamic Republic of)",
    shortName: "IR",
    continent: "Asia",
    zone: "Southern Asia",
  },
  {
    id: 79,
    name: "Iraq",
    shortName: "IQ",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 80,
    name: "Ireland",
    shortName: "IE",
    continent: "Europe",
    zone: "Northern Europe",
  },
  {
    id: 81,
    name: "Israel",
    shortName: "IL",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 82,
    name: "Italy",
    shortName: "IT",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 83,
    name: "Jamaica",
    shortName: "JM",
    continent: "North America",
    zone: "Caribbean",
  },
  {
    id: 84,
    name: "Japan",
    shortName: "JP",
    continent: "Asia",
    zone: "Eastern Asia",
  },
  {
    id: 85,
    name: "Jordan",
    shortName: "JO",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 86,
    name: "Kazakhstan",
    shortName: "KZ",
    continent: "Asia",
    zone: "Central Asia",
  },
  {
    id: 87,
    name: "Kenya",
    shortName: "KE",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 88,
    name: "Kiribati",
    shortName: "KI",
    continent: "Oceania",
    zone: "Micronesia",
  },
  {
    id: 89,
    name: "Kuwait",
    shortName: "KW",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 90,
    name: "Kyrgyzstan",
    shortName: "KG",
    continent: "Asia",
    zone: "Central Asia",
  },
  {
    id: 91,
    name: "Lao People's Democratic Republic",
    shortName: "LA",
    continent: "Asia",
    zone: "Southeast Asia",
  },
  {
    id: 92,
    name: "Latvia",
    shortName: "LV",
    continent: "Europe",
    zone: "Northern Europe",
  },
  {
    id: 93,
    name: "Lebanon",
    shortName: "LB",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 94,
    name: "Lesotho",
    shortName: "LS",
    continent: "Africa",
    zone: "Southern Africa",
  },
  {
    id: 95,
    name: "Liberia",
    shortName: "LR",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 96,
    name: "Libya",
    shortName: "LY",
    continent: "Africa",
    zone: "Northern Africa",
  },
  {
    id: 97,
    name: "Liechtenstein",
    shortName: "LI",
    continent: "Europe",
    zone: "Western Europe",
  },
  {
    id: 98,
    name: "Lithuania",
    shortName: "LT",
    continent: "Europe",
    zone: "Northern Europe",
  },
  {
    id: 99,
    name: "Luxembourg",
    shortName: "LU",
    continent: "Europe",
    zone: "Western Europe",
  },
  {
    id: 100,
    name: "Madagascar",
    shortName: "MG",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 101,
    name: "Malawi",
    shortName: "MW",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 102,
    name: "Malaysia",
    shortName: "MY",
    continent: "Asia",
    zone: "Southeast Asia",
  },
  {
    id: 103,
    name: "Maldives",
    shortName: "MV",
    continent: "Asia",
    zone: "Southern Asia",
  },
  {
    id: 104,
    name: "Mali",
    shortName: "ML",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 105,
    name: "Malta",
    shortName: "MT",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 106,
    name: "Marshall Islands",
    shortName: "MH",
    continent: "Oceania",
    zone: "Micronesia",
  },
  {
    id: 107,
    name: "Mauritania",
    shortName: "MR",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 108,
    name: "Mauritius",
    shortName: "MU",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 109,
    name: "Mexico",
    shortName: "MX",
    continent: "North America",
    zone: "Central America",
  },
  {
    id: 110,
    name: "Micronesia (Federated States of)",
    shortName: "FM",
    continent: "Oceania",
    zone: "Micronesia",
  },
  {
    id: 111,
    name: "Monaco",
    shortName: "MC",
    continent: "Europe",
    zone: "Western Europe",
  },
  {
    id: 112,
    name: "Mongolia",
    shortName: "MN",
    continent: "Asia",
    zone: "Eastern Asia",
  },
  {
    id: 113,
    name: "Montenegro",
    shortName: "ME",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 114,
    name: "Morocco",
    shortName: "MA",
    continent: "Africa",
    zone: "Northern Africa",
  },
  {
    id: 115,
    name: "Mozambique",
    shortName: "MZ",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 116,
    name: "Myanmar",
    shortName: "MM",
    continent: "Asia",
    zone: "Southeast Asia",
  },
  {
    id: 117,
    name: "Namibia",
    shortName: "NA",
    continent: "Africa",
    zone: "Southern Africa",
  },
  {
    id: 118,
    name: "Nauru",
    shortName: "NR",
    continent: "Oceania",
    zone: "Micronesia",
  },
  {
    id: 119,
    name: "Nepal",
    shortName: "NP",
    continent: "Asia",
    zone: "Southern Asia",
  },
  {
    id: 120,
    name: "Netherlands",
    shortName: "NL",
    continent: "Europe",
    zone: "Western Europe",
  },
  {
    id: 121,
    name: "New Zealand",
    shortName: "NZ",
    continent: "Oceania",
    zone: "Australia and New Zealand",
  },
  {
    id: 122,
    name: "Nicaragua",
    shortName: "NI",
    continent: "North America",
    zone: "Central America",
  },
  {
    id: 123,
    name: "Niger",
    shortName: "NE",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 124,
    name: "Nigeria",
    shortName: "NG",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 125,
    name: "North Macedonia",
    shortName: "MK",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 126,
    name: "Norway",
    shortName: "NO",
    continent: "Europe",
    zone: "Northern Europe",
  },
  {
    id: 127,
    name: "Oman",
    shortName: "OM",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 128,
    name: "Pakistan",
    shortName: "PK",
    continent: "Asia",
    zone: "Southern Asia",
  },
  {
    id: 129,
    name: "Palau",
    shortName: "PW",
    continent: "Oceania",
    zone: "Micronesia",
  },
  {
    id: 130,
    name: "Panama",
    shortName: "PA",
    continent: "North America",
    zone: "Central America",
  },
  {
    id: 131,
    name: "Papua New Guinea",
    shortName: "PG",
    continent: "Oceania",
    zone: "Melanesia",
  },
  {
    id: 132,
    name: "Paraguay",
    shortName: "PY",
    continent: "South America",
    zone: "South America",
  },
  {
    id: 133,
    name: "Peru",
    shortName: "PE",
    continent: "South America",
    zone: "South America",
  },
  {
    id: 134,
    name: "Philippines",
    shortName: "PH",
    continent: "Asia",
    zone: "Southeast Asia",
  },
  {
    id: 135,
    name: "Poland",
    shortName: "PL",
    continent: "Europe",
    zone: "Eastern Europe",
  },
  {
    id: 136,
    name: "Portugal",
    shortName: "PT",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 137,
    name: "Qatar",
    shortName: "QA",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 138,
    name: "Republic of Korea",
    shortName: "KR",
    continent: "Asia",
    zone: "Eastern Asia",
  },
  {
    id: 139,
    name: "Republic of Moldova",
    shortName: "MD",
    continent: "Europe",
    zone: "Eastern Europe",
  },
  {
    id: 140,
    name: "Romania",
    shortName: "RO",
    continent: "Europe",
    zone: "Eastern Europe",
  },
  {
    id: 141,
    name: "Russian Federation",
    shortName: "RU",
    continent: "Europe",
    zone: "Eastern Europe",
  },
  {
    id: 142,
    name: "Rwanda",
    shortName: "RW",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 143,
    name: "Saint Kitts and Nevis",
    shortName: "KN",
    continent: "North America",
    zone: "Caribbean",
  },
  {
    id: 144,
    name: "Saint Lucia",
    shortName: "LC",
    continent: "North America",
    zone: "Caribbean",
  },
  {
    id: 145,
    name: "Saint Vincent and the Grenadines",
    shortName: "VC",
    continent: "North America",
    zone: "Caribbean",
  },
  {
    id: 146,
    name: "Samoa",
    shortName: "WS",
    continent: "Oceania",
    zone: "Polynesia",
  },
  {
    id: 147,
    name: "San Marino",
    shortName: "SM",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 148,
    name: "Sao Tome and Principe",
    shortName: "ST",
    continent: "Africa",
    zone: "Middle Africa",
  },
  {
    id: 149,
    name: "Saudi Arabia",
    shortName: "SA",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 150,
    name: "Senegal",
    shortName: "SN",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 151,
    name: "Serbia",
    shortName: "RS",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 152,
    name: "Seychelles",
    shortName: "SC",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 153,
    name: "Sierra Leone",
    shortName: "SL",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 154,
    name: "Singapore",
    shortName: "SG",
    continent: "Asia",
    zone: "Southeast Asia",
  },
  {
    id: 155,
    name: "Slovakia",
    shortName: "SK",
    continent: "Europe",
    zone: "Eastern Europe",
  },
  {
    id: 156,
    name: "Slovenia",
    shortName: "SI",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 157,
    name: "Solomon Islands",
    shortName: "SB",
    continent: "Oceania",
    zone: "Melanesia",
  },
  {
    id: 158,
    name: "Somalia",
    shortName: "SO",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 159,
    name: "South Africa",
    shortName: "ZA",
    continent: "Africa",
    zone: "Southern Africa",
  },
  {
    id: 160,
    name: "South Sudan",
    shortName: "SS",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 161,
    name: "Spain",
    shortName: "ES",
    continent: "Europe",
    zone: "Southern Europe",
  },
  {
    id: 162,
    name: "Sri Lanka",
    shortName: "LK",
    continent: "Asia",
    zone: "Southern Asia",
  },
  {
    id: 163,
    name: "Sudan",
    shortName: "SD",
    continent: "Africa",
    zone: "Northern Africa",
  },
  {
    id: 164,
    name: "Suriname",
    shortName: "SR",
    continent: "South America",
    zone: "South America",
  },
  {
    id: 165,
    name: "Sweden",
    shortName: "SE",
    continent: "Europe",
    zone: "Northern Europe",
  },
  {
    id: 166,
    name: "Switzerland",
    shortName: "CH",
    continent: "Europe",
    zone: "Western Europe",
  },
  {
    id: 167,
    name: "Syrian Arab Republic",
    shortName: "SY",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 168,
    name: "Tajikistan",
    shortName: "TJ",
    continent: "Asia",
    zone: "Central Asia",
  },
  {
    id: 169,
    name: "Thailand",
    shortName: "TH",
    continent: "Asia",
    zone: "Southeast Asia",
  },
  {
    id: 170,
    name: "Timor-Leste",
    shortName: "TL",
    continent: "Asia",
    zone: "Southeast Asia",
  },
  {
    id: 171,
    name: "Togo",
    shortName: "TG",
    continent: "Africa",
    zone: "Western Africa",
  },
  {
    id: 172,
    name: "Tonga",
    shortName: "TO",
    continent: "Oceania",
    zone: "Polynesia",
  },
  {
    id: 173,
    name: "Trinidad and Tobago",
    shortName: "TT",
    continent: "North America",
    zone: "Caribbean",
  },
  {
    id: 174,
    name: "Tunisia",
    shortName: "TN",
    continent: "Africa",
    zone: "Northern Africa",
  },
  {
    id: 175,
    name: "Turkey",
    shortName: "TR",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 176,
    name: "Turkmenistan",
    shortName: "TM",
    continent: "Asia",
    zone: "Central Asia",
  },
  {
    id: 177,
    name: "Tuvalu",
    shortName: "TV",
    continent: "Oceania",
    zone: "Polynesia",
  },
  {
    id: 178,
    name: "Uganda",
    shortName: "UG",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 179,
    name: "Ukraine",
    shortName: "UA",
    continent: "Europe",
    zone: "Eastern Europe",
  },
  {
    id: 180,
    name: "United Arab Emirates",
    shortName: "AE",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 181,
    name: "United Kingdom of Great Britain and Northern Ireland",
    shortName: "GB",
    continent: "Europe",
    zone: "Northern Europe",
  },
  {
    id: 182,
    name: "United Republic of Tanzania",
    shortName: "TZ",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 183,
    name: "United States of America",
    shortName: "US",
    continent: "North America",
    zone: "Northern America",
  },
  {
    id: 184,
    name: "Uruguay",
    shortName: "UY",
    continent: "South America",
    zone: "South America",
  },
  {
    id: 185,
    name: "Uzbekistan",
    shortName: "UZ",
    continent: "Asia",
    zone: "Central Asia",
  },
  {
    id: 186,
    name: "Vanuatu",
    shortName: "VU",
    continent: "Oceania",
    zone: "Melanesia",
  },
  {
    id: 187,
    name: "Venezuela (Bolivarian Republic of)",
    shortName: "VE",
    continent: "South America",
    zone: "South America",
  },
  {
    id: 188,
    name: "Viet Nam",
    shortName: "VN",
    continent: "Asia",
    zone: "Southeast Asia",
  },
  {
    id: 189,
    name: "Yemen",
    shortName: "YE",
    continent: "Asia",
    zone: "Western Asia",
  },
  {
    id: 190,
    name: "Zambia",
    shortName: "ZM",
    continent: "Africa",
    zone: "Eastern Africa",
  },
  {
    id: 191,
    name: "Zimbabwe",
    shortName: "ZW",
    continent: "Africa",
    zone: "Eastern Africa",
  },
];
