export const personalInfo = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    country: "USA",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    country: "Canada",
  },
  {
    id: 3,
    name: "Michael Johnson",
    email: "michael@example.com",
    phone: "456-789-0123",
    country: "UK",
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emily@example.com",
    phone: "789-012-3456",
    country: "Australia",
  },
  {
    id: 5,
    name: "William Brown",
    email: "william@example.com",
    phone: "234-567-8901",
    country: "Germany",
  },
  {
    id: 6,
    name: "Olivia Wilson",
    email: "olivia@example.com",
    phone: "567-890-1234",
    country: "France",
  },
  {
    id: 7,
    name: "James Taylor",
    email: "james@example.com",
    phone: "890-123-4567",
    country: "Japan",
  },
  {
    id: 8,
    name: "Sophia Martinez",
    email: "sophia@example.com",
    phone: "345-678-9012",
    country: "Brazil",
  },
  {
    id: 9,
    name: "Benjamin Anderson",
    email: "benjamin@example.com",
    phone: "678-901-2345",
    country: "Italy",
  },
  {
    id: 10,
    name: "Emma Thomas",
    email: "emma@example.com",
    phone: "901-234-5678",
    country: "Spain",
  },
  {
    id: 11,
    name: "Liam Johnson",
    email: "liam@example.com",
    phone: "234-567-8901",
    country: "USA",
  },
  {
    id: 12,
    name: "Sophia Rodriguez",
    email: "sophia@example.com",
    phone: "567-890-1234",
    country: "Canada",
  },
  {
    id: 13,
    name: "Ethan Kim",
    email: "ethan@example.com",
    phone: "890-123-4567",
    country: "UK",
  },
  {
    id: 14,
    name: "Ava Smith",
    email: "ava@example.com",
    phone: "345-678-9012",
    country: "Australia",
  },
  {
    id: 15,
    name: "Logan Brown",
    email: "logan@example.com",
    phone: "678-901-2345",
    country: "Germany",
  },
  {
    id: 16,
    name: "Mia Jones",
    email: "mia@example.com",
    phone: "901-234-5678",
    country: "France",
  },
  {
    id: 17,
    name: "Noah Wilson",
    email: "noah@example.com",
    phone: "123-456-7890",
    country: "Japan",
  },
  {
    id: 18,
    name: "Charlotte Lee",
    email: "charlotte@example.com",
    phone: "987-654-3210",
    country: "Brazil",
  },
  {
    id: 19,
    name: "Aiden Johnson",
    email: "aiden@example.com",
    phone: "456-789-0123",
    country: "Italy",
  },
  {
    id: 20,
    name: "Amelia Martinez",
    email: "amelia@example.com",
    phone: "789-012-3456",
    country: "Spain",
  },
  {
    id: 21,
    name: "Lucas Thomas",
    email: "lucas@example.com",
    phone: "234-567-8901",
    country: "USA",
  },
  {
    id: 22,
    name: "Isabella Garcia",
    email: "isabella@example.com",
    phone: "567-890-1234",
    country: "Canada",
  },
  {
    id: 23,
    name: "Mason Kim",
    email: "mason@example.com",
    phone: "890-123-4567",
    country: "UK",
  },
  {
    id: 24,
    name: "Evelyn Smith",
    email: "evelyn@example.com",
    phone: "345-678-9012",
    country: "Australia",
  },
  {
    id: 25,
    name: "Harper Brown",
    email: "harper@example.com",
    phone: "678-901-2345",
    country: "Germany",
  },
];
