export const personalInfo = [
  {
    id: 1,
    fullName: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    country: "USA",
  },
  {
    id: 2,
    fullName: "Jane Smith",
    email: "jane@example.com",
    phone: "987-654-3210",
    country: "Canada",
  },
  {
    id: 3,
    fullName: "Michael Johnson",
    email: "michael@example.com",
    phone: "456-789-0123",
    country: "UK",
  },
  {
    id: 4,
    fullName: "Emily Davis",
    email: "emily@example.com",
    phone: "789-012-3456",
    country: "Australia",
  },
  {
    id: 5,
    fullName: "William Brown",
    email: "william@example.com",
    phone: "234-567-8901",
    country: "Germany",
  },
  {
    id: 6,
    fullName: "Olivia Wilson",
    email: "olivia@example.com",
    phone: "567-890-1234",
    country: "France",
  },
  {
    id: 7,
    fullName: "James Taylor",
    email: "james@example.com",
    phone: "890-123-4567",
    country: "Japan",
  },
  {
    id: 8,
    fullName: "Sophia Martinez",
    email: "sophia@example.com",
    phone: "345-678-9012",
    country: "Brazil",
  },
  {
    id: 9,
    fullName: "Benjamin Anderson",
    email: "benjamin@example.com",
    phone: "678-901-2345",
    country: "Italy",
  },
  {
    id: 10,
    fullName: "Emma Thomas",
    email: "emma@example.com",
    phone: "901-234-5678",
    country: "Spain",
  },
  {
    id: 11,
    fullName: "Liam Johnson",
    email: "liam@example.com",
    phone: "234-567-8901",
    country: "USA",
  },
  {
    id: 12,
    fullName: "Sophia Rodriguez",
    email: "sophia@example.com",
    phone: "567-890-1234",
    country: "Canada",
  },
  {
    id: 13,
    fullName: "Ethan Kim",
    email: "ethan@example.com",
    phone: "890-123-4567",
    country: "UK",
  },
  {
    id: 14,
    fullName: "Ava Smith",
    email: "ava@example.com",
    phone: "345-678-9012",
    country: "Australia",
  },
  {
    id: 15,
    fullName: "Logan Brown",
    email: "logan@example.com",
    phone: "678-901-2345",
    country: "Germany",
  },
  {
    id: 16,
    fullName: "Mia Jones",
    email: "mia@example.com",
    phone: "901-234-5678",
    country: "France",
  },
  {
    id: 17,
    fullName: "Noah Wilson",
    email: "noah@example.com",
    phone: "123-456-7890",
    country: "Japan",
  },
  {
    id: 18,
    fullName: "Charlotte Lee",
    email: "charlotte@example.com",
    phone: "987-654-3210",
    country: "Brazil",
  },
  {
    id: 19,
    fullName: "Aiden Johnson",
    email: "aiden@example.com",
    phone: "456-789-0123",
    country: "Italy",
  },
  {
    id: 20,
    fullName: "Amelia Martinez",
    email: "amelia@example.com",
    phone: "789-012-3456",
    country: "Spain",
  },
  {
    id: 21,
    fullName: "Lucas Thomas",
    email: "lucas@example.com",
    phone: "234-567-8901",
    country: "USA",
  },
  {
    id: 22,
    fullName: "Isabella Garcia",
    email: "isabella@example.com",
    phone: "567-890-1234",
    country: "Canada",
  },
  {
    id: 23,
    fullName: "Mason Kim",
    email: "mason@example.com",
    phone: "890-123-4567",
    country: "UK",
  },
  {
    id: 24,
    fullName: "Evelyn Smith",
    email: "evelyn@example.com",
    phone: "345-678-9012",
    country: "Australia",
  },
  {
    id: 25,
    fullName: "Harper Brown",
    email: "harper@example.com",
    phone: "678-901-2345",
    country: "Germany",
  },
];
